version: '3'

services:
  db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306:3306
    command: --wait_timeout=200000 --skip-grant-tables --skip-networking --interactive_timeout=200000 --max_allowed_packet=1073741824 --default-time-zone=+00:00
    environment:
      MYSQL_DATABASE: ${MARIA_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MARIA_DB_PASSWORD}
    volumes:
      - db-mariadb:/var/lib/mysql
  maria-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db-mariadb:
    driver: local
